### PR TITLE
feat: add support for quota project env var

### PR DESCRIPTION
**Pull request by bshaffer**
Alternative implementation to https://github.com/googleapis/google-auth-library-php/pull/452/files

This works:
```php
putenv('GOOGLE_CLOUD_QUOTA_PROJECT=my-quota-project');
// outputs "my-quota-project"
echo CredentialsWrapper::build()->getQuotaProject();
```
This does not:
```php
putenv('GOOGLE_CLOUD_QUOTA_PROJECT=my-quota-project');
// outputs value of "quota_project_id" in the JSON keyfile, or null if one doesn't exist
echo CredentialsWrapper::build(['keyFile' => $keyFilePath])->getQuotaProject(); 
```
But this does:
```php
putenv('GOOGLE_CLOUD_QUOTA_PROJECT=my-quota-project');
putenv('GOOGLE_APPLICATION_CREDENTIALS=' . $keyFilePath);
// outputs "my-quota-project" regardless of what is in the JSON keyfile
echo CredentialsWrapper::build()->getQuotaProject(); 
```

cc @TimurSadykov

### CODE REVIEW

**Comment by bshaffer** [comment]
@sai-sunder-s the main reason is that the env var is `GOOGLE_CLOUD_`, so it doesn't seem like it should apply to generic auth rules.

**Comment by sai-sunder-s** [comment]
Auth library in some languages already support `GOOGLE_CLOUD_` env vars. eg: `GOOGLE_CLOUD_PROJECT`.

`GOOGLE_CLOUD_QUOTA_PROJECT` is part of [AIP](https://google.aip.dev/auth/4110).

**Comment by bshaffer** [comment]
That is not the case in PHP, we support `GOOGLE_CLOUD_PROJECT` only as part of our `google/cloud-core` package.

**Comment by bshaffer** [comment]
@sai-sunder-s sounds good to me! I reopened https://github.com/googleapis/google-auth-library-php/pull/452

**Comment by bshaffer** [comment]
Closing in favor of implementing in `google/auth`

**Pull request closed without merging**
