### PR TITLE
chore: prepare 1.5.0

### PR DESCRIPTION
**Pull request by jdpedrie**
### Features

* feat: default to self-signed JWTs and use updateMetadata for fetching tokens (#272)

### Fixes

* autoloading of metadata classes (#278)
* namespace fixes (#279)
* enable non-slash resource name separators (#284)
* use non-slash separators when constructing relative PathTemplates (#288)

### CODE REVIEW

**Comment by dwsupplee** [comment]
Let's please add https://github.com/googleapis/gax-php/pull/272 as well

**Comment by jdpedrie** [comment]
@dwsupplee it done

**Review by bshaffer — APPROVED** [review]

**Review by bshaffer — CHANGES_REQUESTED** [review]
I am investigating an issue I found in `google/cloud` as a result of our last change.

**Comment by bshaffer** [comment]
We also should merge https://github.com/googleapis/google-auth-library-php/pull/310, otherwise the new version of `gax` will result in a variable undefined error in some cases.

**Review by bshaffer — APPROVED** [review]

**Comment by dwsupplee** [comment]
@jdpedrie we have one more important fix to include, can we please add https://github.com/googleapis/gax-php/pull/288? :)

**Comment by jdpedrie** [comment]
@dwsupplee done!

**Review by dwsupplee — APPROVED** [review]

**Review by miraleung — APPROVED** [review]

**Comment by dwsupplee** [comment]
@jdpedrie Merging now if you would like to tag

**Pull request merged**
