### PR TITLE
chore: replace sami with doctum for doc generation

### PR DESCRIPTION
**Pull request by williamdes**
## Replace Sami by [Doctum](https://github.com/code-lts/doctum#readme)

Work done:
- Replaced Sami by [Doctum](https://github.com/code-lts/doctum#readme)
- Add a .gitattributes file to clean vendor tarball

I have some other @googleapis repos to do if this one is accepted: https://github.com/search?p=2&q=org%3Agoogleapis+sami&type=Code

### CODE REVIEW

**Comment by jdpedrie** [comment]
Thanks @williamdes, good to see someone has picked up support for Sami!

I think this is fine for gax, but for other libraries we may have some issues. Specifically, we need support for nested array declarations (i.e. `$options.foo`). Sami doesn't support these out of the box, and so I hacked them in, in what is likely a terrible injustice to the library. Any chance the fork will support that anytime soon, or is it just a project to continue basic maintenance?

**Comment by williamdes** [comment]
> I think this is fine for gax, but for other libraries we may have some issues. Specifically, we need support for nested array declarations (i.e. $options.foo). Sami doesn't support these out of the box, and so I hacked them in, in what is likely a terrible injustice to the library. Any chance the fork will support that anytime soon, or is it just a project to continue basic maintenance?

Well this is interesting, would you mind opening an issue on Doctum ?
I am open to add new features, this is maintenance + new features if time can be found to make them.
I welcome pull-requests as well, you seem to have coded this part :)

**Comment by williamdes** [comment]
Hi @jdpedrie 
Would you agree to merge this pull-request so I can move forward on @googleapis ?

**Comment by jdpedrie** [comment]
Sorry for the delay @williamdes. Looks like the tests are failing on older PHP versions. I think the safest way to fix this, in versions of PHP below 7.1, would be something like this:

```
composer install --ignore-platform-reqs
composer remove code-lts/doctum
composer update
```

The last update will verify that there are no other PHP version conflicts.

We'll also want to bump [this](https://github.com/googleapis/gax-php/blob/master/.travis.yml#L45) to 7.1. :)

Thanks again for tackling this!

**Comment by williamdes** [comment]
> Sorry for the delay @williamdes. Looks like the tests are failing on older PHP versions. I think the safest way to fix this, in versions of PHP below 7.1, would be something like this:
> 
> ```
> composer install --ignore-platform-reqs
> composer remove code-lts/doctum
> composer update
> ```
> 
> The last update will verify that there are no other PHP version conflicts.
> 
> We'll also want to bump [this](https://github.com/googleapis/gax-php/blob/master/.travis.yml#L45) to 7.1. :)
> 
> Thanks again for tackling this!

Thank you for the update !

It should work fine now, let's see if the CI agrees.

**Review by jdpedrie — APPROVED** [review]

**Comment by williamdes** [comment]
Hi @jdpedrie 
The CI does not removed deleted files, I fixed that in https://github.com/googleapis/gax-php/pull/292

**Pull request merged**
